#!/usr/bin/env python
# Copyright 2011 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import logging
import optparse
import os
import platform
import re
import sys

import src.browser as browser
from src.frontend_download import FrontendDownload
from src.frontend_daemon_host import FrontendDaemonHost
import src.deps as deps

def main(args):
  host = None
  try:
    print "Updating frontend code from %s..." % deps.CHROME_SVN_BASE
    dl = FrontendDownload(deps.CHROME_SVN_BASE, deps.CHROME_SVN_REV)
    host = FrontendDaemonHost(23252, dl.data_dir)
    b = browser.Browser()
    b.load_url(host.baseurl)
    b.show()
    browser.run_main_loop()
  finally:
    if host:
      host.close() # prevent host from leaking its daemon
  

if __name__ == '__main__':
  os.chdir(os.path.dirname(__file__))
  if platform.system() == 'Darwin':
    if os.getenv('VERSIONER_PYTHON_PREFER_32_BIT') != 'yes':
      os.putenv('VERSIONER_PYTHON_PREFER_32_BIT', 'yes')
      args = [sys.executable]
      args.extend(sys.argv)
      os.execv(args[0], args)
    else:
      sys.exit(main(sys.argv[1:]))
  else:
    sys.exit(main(sys.argv[1:]))
